Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-Kingston_HyperX_QuadCast_S_4101-00.analog-stereo"
LastUsedOutput = ""
